### ISSUE TITLE
Missing Apache 2 license

### ISSUE THREAD

**Issue by dtolnay** [bincode-org/unty#4]
According to the Cargo.toml metadata and readme, the crate is dual licensed "MIT OR Apache-2.0", but only an MIT license is currently present in the repo. 

https://github.com/bincode-org/unty/blob/2f2379c90595d4bcbe9244e9a9bbbb6cfaac611c/Cargo.toml#L6

https://github.com/bincode-org/unty/blob/2f2379c90595d4bcbe9244e9a9bbbb6cfaac611c/README.md#L27

As far as I understand it, the Apache 2.0 license requires that you distribute the license text together with the sources: _"You must give any other recipients of the Work or Derivative Works a copy of this License"_.

**Comment by VictorKoenders** [comment]
I copied this from bincode, which I thought was MIT OR Apache-2.0, but apparently it's only MIT. thanks for reporting
